# Generated by Django 2.2.17 on 2020-11-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('propietario', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='AduanaNacional/objetos/')),
                ('zona', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=20)),
                ('administracion', models.CharField(max_length=20)),
            ],
        ),
    ]
