# Generated by Django 2.2.17 on 2020-12-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AduanaNacional', '0002_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
